version: '3.7'
services:
  db:
    image: mariadb:10.6.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=clico
      - MYSQL_DATABASE=clico
      - MYSQL_USER=clico
      - MYSQL_PASSWORD=clico
      - TERM=dumb
    volumes:
      - ./maria/mysql:/var/lib/mysql
      - ./docker/db/:/etc/mysql/mariadb.conf.d/
  api:
    build: ./docker/php
    tty: true
    volumes:
      - ./api:/application
      - ./docker/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf

    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "85:80"
    links:
      - db
  webserver:
    image: nginx
    working_dir: /application
    volumes:
      - ./api:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
      - phpmyadmin
  composer:
    build: docker/composer
    working_dir: /application
    volumes:
      - ./api:/application
  angular:
    build: docker/node
    volumes:
      - ./front/:/src
    tty: true
    ports:
      - "4200:4200"
  cdn:
    build: docker/node
    volumes:
      - ./cdn/:/src
    tty: true
    ports:
      - "8081:80"

