jms_serializer:
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            entity:
                namespace_prefix: "App\\Entity"
                path: "%kernel.project_dir%/src/Resources/config/serializer/entity"
            model:
                namespace_prefix: "App\\Model"
                path: "%kernel.project_dir%/src/Resources/config/serializer/model"
