App\Model\Passwords:
  exclusion_policy: all
  xml_root_name: page
  access_order: alphabetical
  properties:
    oldPassword:
      type: string
      groups: [input, output]
    newPassword:
      type: string
      groups: [ input, output ]
