App\Entity\Picture:
  exclusion_policy: all
  xml_root_name: page
  access_order: alphabetical
  properties:
    id:
      type: integer
      groups: [input, output,pv]
    file:
      type: string
      groups: [input, output,pv, product]

