App\Entity\Product:
  exclusion_policy: all
  xml_root_name: page
  access_order: alphabetical
  properties:
    shopUuid:
      type: string
      groups: [input, output,pv]
    uuid:
      type: string
      groups: [input, output,pv]
    name:
      type: string
      groups: [input, output,pv]
    price:
      type: float
      groups: [input, output,pv]
    label:
      type: string
      groups: [input, output,pv]
    pictures:
      type: ArrayCollection<App\Entity\Picture>
      groups: [input, output,pv]
