App\Entity\User:
  exclusion_policy: all
  xml_root_name: page
  access_order: alphabetical
  properties:
    email:
      type: string
      groups: [input, output]
    password:
      type: string
      groups: [input,output]
    name:
      type: string
      groups: [ input,output ]
